webtalk_init -webtalk_dir C:/Users/User/Desktop/STM/Lab3/Array_Multiplier/Array_Multiplier/Array_Multiplier.sim/sim_1/impl/func/xsim/xsim.dir/array_mul_tb_func_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 10 23:16:06 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "48042fde-f5e4-463e-9504-40bcc6fe3b9a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "96af0d9bc1fb4b40b022f05c428e9e95" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5800H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key saif -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "20960_KB" -context "xsim\\usage"
webtalk_transmit -clientid 695541780 -regid "" -xml C:/Users/User/Desktop/STM/Lab3/Array_Multiplier/Array_Multiplier/Array_Multiplier.sim/sim_1/impl/func/xsim/xsim.dir/array_mul_tb_func_impl/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/User/Desktop/STM/Lab3/Array_Multiplier/Array_Multiplier/Array_Multiplier.sim/sim_1/impl/func/xsim/xsim.dir/array_mul_tb_func_impl/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/User/Desktop/STM/Lab3/Array_Multiplier/Array_Multiplier/Array_Multiplier.sim/sim_1/impl/func/xsim/xsim.dir/array_mul_tb_func_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
